version: "3"
services:
  student_service:
    build: . # This tells Docker Compose to build the image using your Dockerfile in the current directory.
    restart: unless-stopped
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://mongo:27017
      MONGO_DB: student_db
    ports:
      - "8080:8080"

  mongo:
    restart: unless-stopped
    image: mongo:4
    ports:
      - "27017:27017"
